<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56c451486dc12',
	'title' => 'Finishes Options',
	'fields' => array (
		array (
			'key' => 'field_56c4514888f7d',
			'label' => 'Swatch Repeater',
			'name' => 'swatch_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Swatch',
			'sub_fields' => array (
				array (
					'key' => 'field_56c45148972c6',
					'label' => 'Swatch Image',
					'name' => 'swatch_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56c451489735a',
					'label' => 'Color Code',
					'name' => 'color_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56c45148973e4',
					'label' => 'Color Name',
					'name' => 'color_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'finish',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56be0498188cc',
	'title' => 'Wood Options',
	'fields' => array (
		array (
			'key' => 'field_56be04a044015',
			'label' => 'Swatch Repeater',
			'name' => 'swatch_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Swatch',
			'sub_fields' => array (
				array (
					'key' => 'field_56be04c744016',
					'label' => 'Swatch Image',
					'name' => 'swatch_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56be055c5885d',
					'label' => 'Color Code',
					'name' => 'color_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56be05665885e',
					'label' => 'Color Name',
					'name' => 'color_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wood',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56bd97be159e6',
	'title' => 'Fabric Options',
	'fields' => array (
		array (
			'key' => 'field_56bd97d29f645',
			'label' => 'Swatch Repeater',
			'name' => 'swatch_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_56bd97ea9f646',
					'label' => 'Swatch Image',
					'name' => 'swatch_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56bd98469f647',
					'label' => 'Color Code',
					'name' => 'color_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56bd985a9f648',
					'label' => 'Color Name',
					'name' => 'color_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'fabric',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56bc8e73cc54a',
	'title' => 'Product Options',
	'fields' => array (
		array (
			'key' => 'field_56bc8f2753252',
			'label' => 'Product Description',
			'name' => 'product_description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_56bc8eaa53250',
			'label' => 'Product Gallery Repeater',
			'name' => 'product_gallery_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => 7,
			'layout' => 'table',
			'button_label' => 'Add Product Shot',
			'sub_fields' => array (
				array (
					'key' => 'field_56bc8eff53251',
					'label' => 'Product Image',
					'name' => 'product_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_56bc8f4a53253',
			'label' => 'Vinyl Fabric Relationship',
			'name' => 'vinyl_fabric_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'fabric',
			),
			'taxonomy' => array (
				0 => 'fabric-category:vinyl',
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56bdaef09894a',
			'label' => 'Weave Fabric Relationship',
			'name' => 'weave_fabric_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'fabric',
			),
			'taxonomy' => array (
				0 => 'fabric-category:weave',
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56bdc53bc92a2',
			'label' => 'Wood Relationship',
			'name' => 'wood_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'wood',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56bde14ac92a3',
			'label' => 'Finishes Relationship',
			'name' => 'finishes_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'finish',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'product',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56056433756c8',
	'title' => '0 Global Page Options',
	'fields' => array (
		array (
			'key' => 'field_5605644bac1b9',
			'label' => 'Custom Page Title',
			'name' => 'custom_page_title',
			'type' => 'text',
			'instructions' => 'Define a better page title instead of the one generated automatically by the CMS',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_560564b7ac1ba',
			'label' => 'Enable Page Gallery',
			'name' => 'enable_page_gallery',
			'type' => 'true_false',
			'instructions' => 'Tick the box to enable the custom slideshow editor',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the custom slideshow editor',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5605651aac1bb',
			'label' => 'Slideshow Repeater',
			'name' => 'slideshow_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560564b7ac1ba',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add New Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_5605654eac1bc',
					'label' => 'Slide Image',
					'name' => 'slide_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 1920,
					'max_height' => 1080,
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_566aeda51f7ab',
					'label' => 'Enable Captions',
					'name' => 'enable_captions',
					'type' => 'true_false',
					'instructions' => 'Enable this option to add captions to the slide',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_560905a2d0fad',
					'label' => 'Caption',
					'name' => 'caption',
					'type' => 'wysiwyg',
					'instructions' => 'Enter Individual caption line to describe this slide',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_566aeda51f7ab',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_56090622d0fae',
					'label' => 'Shot Location',
					'name' => 'shot_location',
					'type' => 'text',
					'instructions' => 'Enter the shot location',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_564d9a434e1f3',
			'label' => 'Enable Case Studies',
			'name' => 'enable_case_studies',
			'type' => 'true_false',
			'instructions' => 'Tick this box to enable the related case studies module for this page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable the case studies module',
			'default_value' => 0,
		),
		array (
			'key' => 'field_564d9aa94e1f4',
			'label' => 'Case Studies Relationship',
			'name' => 'case_studies_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_564d9a434e1f3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'case-studies',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => 3,
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_564da6565b234',
			'label' => 'Enable Call To Action',
			'name' => 'enable_call_to_action',
			'type' => 'true_false',
			'instructions' => 'Tick this box to enable a call to action module for this page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56bc4241e7a64',
			'label' => 'CTA Relationship',
			'name' => 'cta_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_564da6565b234',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'call-to-action',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => 1,
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case-studies',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56b889485bbb1',
	'title' => '0.1 CTA Options',
	'fields' => array (
		array (
			'key' => 'field_56bafac7db2e8',
			'label' => 'CTA Background',
			'name' => 'cta_background',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56bafadadb2e9',
			'label' => 'CTA Statement',
			'name' => 'cta_statement',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56bb56e330892',
			'label' => 'CTA Button Label',
			'name' => 'cta_button_label',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56bb1872db2ea',
			'label' => 'CTA Location',
			'name' => 'cta_location',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56bb189adb2eb',
			'label' => 'CTA Overlay Color',
			'name' => 'cta_overlay_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2c3c3b',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'call-to-action',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_569f94f33967d',
	'title' => '1 Home Page Options',
	'fields' => array (
		array (
			'key' => 'field_569f94f74aad2',
			'label' => 'introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => 'Format an introductory paragraph',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_56af204dae1e1',
			'label' => 'About Relationship',
			'name' => 'about_relationship',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'filters' => '',
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56a00c1ce33bd',
			'label' => 'Case Study Relationship',
			'name' => 'case_study_relationship',
			'type' => 'relationship',
			'instructions' => 'Select some case studies to draw attention and upsell',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'case-studies',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56a2d59c1171a',
			'label' => 'Clients Repeater',
			'name' => 'clients_repeater',
			'type' => 'repeater',
			'instructions' => 'Select Clients Logos to feature on the home page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Logo',
			'sub_fields' => array (
				array (
					'key' => 'field_56a2d5c11171b',
					'label' => 'Client Image',
					'name' => 'client_image',
					'type' => 'image',
					'instructions' => 'Select an individual logo for each client to feature',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '43',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_568a98fcb71ed',
	'title' => '2 Services Options',
	'fields' => array (
		array (
			'key' => 'field_56a73231e300c',
			'label' => 'introduction',
			'name' => 'introduction',
			'type' => 'wysiwyg',
			'instructions' => 'Format an introductory paragraph',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_56a74149152a0',
			'label' => 'Sub Page Relationship',
			'name' => 'sub_page_relationship',
			'type' => 'relationship',
			'instructions' => 'Select the Sub Pages to Display',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'filters' => '',
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '711',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '45',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56a7ddfc241d0',
	'title' => '2.1 Information Page Options',
	'fields' => array (
		array (
			'key' => 'field_56a7de4403465',
			'label' => 'Gallery Repeater',
			'name' => 'gallery_repeater',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56a7de6303466',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_56a7de6303466',
					'label' => 'Gallery Image',
					'name' => 'gallery_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1049',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1036',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1040',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1046',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1965',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1961',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1967',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '1963',
			),
		),
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '47',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56602f37b0f38',
	'title' => '4 Case Studies Options',
	'fields' => array (
		array (
			'key' => 'field_56602f6cb8158',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => 'Describe what work was carried out at this location',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56a8c5bef3a08',
			'label' => 'Geographical',
			'name' => 'geographical',
			'type' => 'text',
			'instructions' => 'Enter the part of the country this Job was completed in',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'case-studies',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5654dcee8c118',
	'title' => '5 Contact Options',
	'fields' => array (
		array (
			'key' => 'field_5655c8439cbbd',
			'label' => 'Map Origin Coordinates',
			'name' => 'map_origin_coordinates',
			'type' => 'text',
			'instructions' => 'Enter the coordinates for the map to start at',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '52.7147023, -2.7496869',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5655c8b19cbbe',
			'label' => 'Map Zoom Level',
			'name' => 'map_zoom_level',
			'type' => 'number',
			'instructions' => 'Choose the zoom level that the map will focus at',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 7,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5655c8e39cbbf',
			'label' => 'Map Marker Icon',
			'name' => 'map_marker_icon',
			'type' => 'image',
			'instructions' => 'Choose an icon image for the branch map markers',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5655c91a9cbc0',
			'label' => 'Contact form Counties',
			'name' => 'contact_form_counties',
			'type' => 'textarea',
			'instructions' => 'Enter the counties available for section. Separate with commas.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Aberdeenshire,Anglesey,Angus,Argyll & Bute,Ayrshire,Bedfordshire,Berkshire,Blaenau Gwent,Borders,Bridgend,Bristol,Buckinghamshire,Caerphilly,Carmarthenshire,Cambridgeshire,Cardiff,Ceredigion,Cheshire,City of Edinburgh,City of Glasgow,Clackmannanshire,Conwy,Cornwall,County Antrim,County Armagh,County Down,County Fermanagh,County Londonderry,County Tyrone,Cumbria,Denbighshire,Derbyshire,Devon,Dorset,Dumfries Galloway,Dundee City,Durham,East Sussex,East Riding of Yorkshire,Edinburgh (City of),Essex,Falkirk,Fife,Flintshire,Greater London,Greater Manchester,Glasgow (City of),Gloucestershire,Gwynedd,Hampshire,Herefordshire,Hertfordshire,Highlands,Isle of Man,Isle of Skye,Isle of Wight,Kent,Kirkcudbrightshire,Lanarkshire,Lancashire,Leicestershire,Lincolnshire,London,Lothian,Manchester,Merseyside,Monmouthshire,Moray,Neath Port Talbot,Newport,Norfolk,North Yorkshire,Northamptonshire,Northumberland,Nottinghamshire,Orkney,Oxfordshire,Pembrkeshire,Perth Kinross,Powys,Renfrewshire,Rhondda Cynon Taff,Shetland Isles,Shropshire,Somerset,South Yorkshire,Staffordshire,Stirlingshire,Suffolk,Surrey,Swansea,Torfaen,Tyne Wear,Vale of Glamorgan,Warwickshire,West Midlands,West Sussex,West Yorkshire,Western Isles,Wiltshire,Worcestershire,Wrexham',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5655c9b09cbc1',
			'label' => 'Enquiry Type Repeater',
			'name' => 'enquiry_type_repeater',
			'type' => 'repeater',
			'instructions' => 'Add Enquiry Types available for section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_5655c9e29cbc2',
					'label' => 'Enquiry Type',
					'name' => 'enquiry_type',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => 'Enquiry Type',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_5655ca149cbc3',
			'label' => 'Methods Repeater',
			'name' => 'methods_repeater',
			'type' => 'repeater',
			'instructions' => 'Add methods people used to find Harris Contract Furniture.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_5655ca3b9cbc4',
					'label' => 'Method',
					'name' => 'method',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => 'Method',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page',
				'operator' => '==',
				'value' => '51',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5655d17bdd3ca',
	'title' => '5.1 Branch Options',
	'fields' => array (
		array (
			'key' => 'field_5655d18b9f3a1',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'text',
			'instructions' => 'Enter phone number for branch',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5655d1aa9f3a2',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'textarea',
			'instructions' => 'Enter address of Branch here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5655d1c99f3a3',
			'label' => 'Map Coordinates',
			'name' => 'map_coordinates',
			'type' => 'text',
			'instructions' => 'Enter Lat Lng coordinates for this branch',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'branch',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
?>